load("@fbcode_macros//build_defs:python_binary.bzl", "python_binary")
load("@fbcode_macros//build_defs:python_unittest.bzl", "python_unittest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("ml_oncall")

python_binary(
    name = "contract_smoke",
    srcs = ["contract_smoke.py"],
    base_module = "",
    main_function = "contract_smoke.main",
    typing = False,
    deps = [
        "fbsource//third-party/pypi/attrs:attrs",
        "//_tony_dev/CoreProjects/AgentFoundation/src:agent_foundation",
    ],
)

python_unittest(
    name = "test_output_guardrail",
    srcs = ["test_output_guardrail.py"],
    base_module = "",
    typing = False,
    deps = [
        "fbsource//third-party/pypi/attrs:attrs",
        "//_tony_dev/CoreProjects/AgentFoundation/src:agent_foundation",
        "//_tony_dev/CoreProjects/RichPythonUtils/src:rich_python_utils",
    ],
)

python_unittest(
    name = "test_research_propose_contract",
    srcs = ["test_research_propose_contract.py"],
    base_module = "",
    typing = False,
    deps = [
        "//_tony_dev/CoreProjects/AgentFoundation/src:agent_foundation",
        "//_tony_dev/CoreProjects/RichPythonUtils/src:rich_python_utils",
    ],
)

python_unittest(
    name = "test_breakdown_block_registry",
    srcs = ["test_breakdown_block_registry.py"],
    base_module = "",
    typing = False,
    deps = [
        "fbsource//third-party/pypi/attrs:attrs",
        "//_tony_dev/CoreProjects/AgentFoundation/src:agent_foundation",
    ],
)

python_unittest(
    name = "test_bta_resume_original_query",
    srcs = ["test_bta_resume_original_query.py"],
    base_module = "",
    typing = False,
    deps = [
        "fbsource//third-party/pypi/attrs:attrs",
        "//_tony_dev/CoreProjects/AgentFoundation/src:agent_foundation",
    ],
)

python_unittest(
    name = "test_bta_resume_workspace_binding",
    srcs = ["test_bta_resume_workspace_binding.py"],
    typing = False,
    deps = [
        "fbsource//third-party/pypi/attrs:attrs",
        "//_tony_dev/CoreProjects/AgentFoundation/src:agent_foundation",
    ],
)

python_unittest(
    name = "test_task_instructions_snapshot",
    srcs = ["test_task_instructions_snapshot.py"],
    base_module = "",
    typing = False,
    deps = [
        "fbsource//third-party/pypi/attrs:attrs",
        "//_tony_dev/CoreProjects/AgentFoundation/src:agent_foundation",
        "//_tony_dev/CoreProjects/RichPythonUtils/src:rich_python_utils",
    ],
)

python_unittest(
    name = "test_reviewer_guardrail_cascade",
    srcs = ["test_reviewer_guardrail_cascade.py"],
    base_module = "",
    typing = False,
    deps = [
        "fbsource//third-party/pypi/attrs:attrs",
        "//_tony_dev/CoreProjects/AgentFoundation/src:agent_foundation",
    ],
)

python_unittest(
    name = "test_streaming_recovery",
    srcs = ["test_streaming_recovery.py"],
    typing = False,
    deps = [
        "fbsource//third-party/pypi/attrs:attrs",
        "fbsource//third-party/pypi/hypothesis:hypothesis",
        "//_tony_dev/CoreProjects/AgentFoundation/src:agent_foundation",
    ],
)

python_unittest(
    name = "test_bta_checkpoint_promotion",
    srcs = ["test_bta_checkpoint_promotion.py"],
    base_module = "",
    typing = False,
    deps = [
        "fbsource//third-party/pypi/attrs:attrs",
        "//_tony_dev/CoreProjects/AgentFoundation/src:agent_foundation",
    ],
)

python_unittest(
    name = "test_bta_worker_resume",
    srcs = ["test_bta_worker_resume.py"],
    base_module = "",
    typing = False,
    deps = [
        "fbsource//third-party/pypi/attrs:attrs",
        "//_tony_dev/CoreProjects/AgentFoundation/src:agent_foundation",
    ],
)

python_unittest(
    name = "test_breakdown_then_aggregate",
    srcs = ["test_breakdown_then_aggregate.py"],
    base_module = "",
    typing = False,
    deps = [
        "fbsource//third-party/pypi/attrs:attrs",
        "//_tony_dev/CoreProjects/AgentFoundation/src:agent_foundation",
        "//_tony_dev/CoreProjects/RichPythonUtils/src:rich_python_utils",
    ],
)

python_unittest(
    name = "test_function_inferencer",
    srcs = ["test_function_inferencer.py"],
    network_access = network_access_utils.none(),
    typing = False,
    deps = [
        "//_tony_dev/CoreProjects/AgentFoundation/src:agent_foundation",
        "//_tony_dev/CoreProjects/RichPythonUtils/src:rich_python_utils",
    ],
)

python_unittest(
    name = "test_inferencer_variable_expansion",
    srcs = ["test_inferencer_variable_expansion.py"],
    network_access = network_access_utils.none(),
    typing = False,
    deps = [
        "fbsource//third-party/pypi/attrs:attrs",
        "//_tony_dev/CoreProjects/AgentFoundation/src:agent_foundation",
        "//_tony_dev/CoreProjects/RichPythonUtils/src:rich_python_utils",
    ],
)
