load("@fbcode_macros//build_defs:python_pytest.bzl", "python_pytest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("ml_oncall")

python_pytest(
    name = "test_evaluator",
    srcs = ["test_evaluator.py"],
    network_access = network_access_utils.none(),
    typing = False,
    deps = [
        "fbsource//third-party/pypi/pytest:pytest",
        "//_tony_dev/CoreProjects/AgentFoundation/src:agent_foundation",
    ],
)
