BEDROCK_SERVICE_NAME_BEDROCK_RUNTIME = 'bedrock-runtime'
BEDROCK_SERVICE_REGION_US_EAST1 = 'us-east-1'
BEDROCK_SERVICE_REGION_US_WEST1 = 'us-west-1'
BEDROCK_SERVICE_REGION_US_WEST2 = 'us-west-2'
BEDROCK_RUNTIME_SERVICE_URL_PREFIX = 'https://'
BEDROCK_RUNTIME_SERVICE_URL_PATTERN = BEDROCK_RUNTIME_SERVICE_URL_PREFIX + "bedrock-runtime.{region}.amazonaws.com"
