load("@fbcode_macros//build_defs:python_pytest.bzl", "python_pytest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("ml_oncall")

python_pytest(
    name = "terminal_inferencers",
    srcs = glob(["test_*.py"]),
    network_access = network_access_utils.none(),
    typing = False,
    deps = [
        "fbsource//third-party/pypi/attrs:attrs",
        "fbsource//third-party/pypi/pytest:pytest",
        "//_tony_dev/CoreProjects/AgentFoundation/src:agent_foundation",
        "//_tony_dev/CoreProjects/AgentFoundation/src/agent_foundation/common/inferencers/agentic_inferencers/external/metamate:metamate_lib",
        "//_tony_dev/CoreProjects/RichPythonUtils/src:rich_python_utils",
        "//later:lib",
    ],
)
