#!/usr/bin/env python3
"""Codegen: widget_protocol.py + input_modes.py → *.js modules.

Ensures Python widget-type constants and InputMode enum values are mirrored
exactly in JavaScript. CI runs --check to fail on drift.

Usage:
    python scripts/sync_widget_types.py            # write
    python scripts/sync_widget_types.py --check    # CI guard
    python scripts/sync_widget_types.py --protocol-path /path/to/src
                                                   # standalone mode
"""
from __future__ import annotations
import argparse, difflib, importlib, pathlib, sys


def _load_protocol(protocol_path: pathlib.Path | None):
    if protocol_path is not None:
        sys.path.insert(0, str(protocol_path))
    wp = importlib.import_module('agent_foundation.ui.widget_protocol')
    im = importlib.import_module('agent_foundation.ui.input_modes')
    return wp.WIDGET_TYPES, im.InputMode


HERE = pathlib.Path(__file__).resolve().parent.parent
BANNER = "// AUTOGENERATED — DO NOT EDIT. Run scripts/sync_widget_types.py.\n"


def _const(t: str) -> str:
    return "WIDGET_" + t.upper()


def render_widget_types(widget_types) -> str:
    out = [BANNER, "// Mirrors agent_foundation.ui.widget_protocol.WIDGET_TYPES\n"]
    for t in widget_types:
        out.append(f"export const {_const(t)} = {t!r};\n")
    out.append("export const WIDGET_TYPES = Object.freeze([\n")
    out.extend(f"  {t!r},\n" for t in widget_types)
    out.append("]);\n")
    return "".join(out)


def render_input_mode_types(input_mode_enum) -> str:
    out = [BANNER, "// Mirrors agent_foundation.ui.input_modes.InputMode\n",
           "export const InputMode = Object.freeze({\n"]
    out.extend(f"  {m.name}: {m.value!r},\n" for m in input_mode_enum)
    out.append("});\n")
    return "".join(out)


def _write_or_check(path: pathlib.Path, content: str, check: bool) -> bool:
    if check:
        cur = path.read_text() if path.exists() else ""
        if cur == content:
            return True
        sys.stderr.write("".join(difflib.unified_diff(
            cur.splitlines(True), content.splitlines(True),
            fromfile=str(path), tofile="generated")))
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if generated files are stale")
    ap.add_argument("--protocol-path", type=pathlib.Path, default=None,
                    help="directory containing agent_foundation package on sys.path")
    args = ap.parse_args()
    widget_types, input_mode = _load_protocol(args.protocol_path)
    ok = True
    ok &= _write_or_check(
        HERE / "src/protocol/widgetTypes.js",
        render_widget_types(widget_types),
        args.check,
    )
    ok &= _write_or_check(
        HERE / "src/protocol/inputModeTypes.js",
        render_input_mode_types(input_mode),
        args.check,
    )
    if not args.check:
        print(f"Generated {HERE / 'src/protocol/widgetTypes.js'}")
        print(f"Generated {HERE / 'src/protocol/inputModeTypes.js'}")
    sys.exit(0 if ok else 1)
