from abc import ABC
from typing import Any

from attr import attrs, attrib

from science_modeling_tools.ui.interactive_base import InteractiveBase, InteractionFlags
from webaxon.html_utils.common import is_html_string


@attrs
class TerminalInteractive(InteractiveBase, ABC):
    """
    A terminal-based implementation of `InteractiveBase` for interacting with users through
    text input and output in the terminal.

    This class provides methods for capturing user input, displaying responses, and resetting
    the input state, allowing for text-based interactive sessions.

    Methods:
        get_input() -> str:
            Prompts the user for input in the terminal and returns their response as a string.

        reset_input(flag: InteractionFlags) -> None:
            Resets the input state, typically by printing a divider in the terminal to indicate
            the start of a new interaction.

        send_response(response: str, flag: InteractionFlags) -> None:
            Outputs the response to the terminal and invokes `reset_input` to prepare for the next interaction.
    """

    pending_message: str = attrib(default="Awaiting further input ...")

    def _get_input(self) -> str:
        """
        Captures input from the user in the terminal.

        Prompts the user to enter text and returns the input as a string.

        Returns:
            str: The raw input text entered by the user.
        """
        return input(f"{self.user_name}: ")

    def reset_input(self, flag: InteractionFlags) -> None:
        """
        Resets the input state in the terminal.

        This implementation can display a divider or message indicating the interaction state.
        Currently a no-op implementation.

        Args:
            flag (InteractionFlags): The interaction state flag.
                - PendingInput: Agent is waiting for user input
                - MessageOnly: Agent sent a message but will continue working
                - TurnCompleted: Agent's turn is complete
        """
        pass

    def _send_pending_message(self):
        print(f"\n\n{self.pending_message}")

    def _send_response(self, response: Any, flag: InteractionFlags = InteractionFlags.TurnCompleted) -> None:
        """
        Sends the response to the user in the terminal.

        Displays the response text in the terminal, prefixed with `system_name`, to provide
        a clear, readable interaction experience.

        Args:
            response (str): The response text generated by the agent.
            flag (InteractionFlags): The interaction state flag.
                - PendingInput: Agent is waiting for user input
                - MessageOnly: Agent sent a message but will continue working
                - TurnCompleted: Agent's turn is complete (default)
        """

        response = str(response)

        if is_html_string(response):
            import tempfile
            import webbrowser

            with tempfile.NamedTemporaryFile('w', delete=False, suffix='.html', encoding='utf-8') as f:
                f.write(response)
                temp_filename = f.name

            print(temp_filename)
            print("Displaying response in your default web browser ...")
            webbrowser.open('file://' + temp_filename)
        else:
            print(self.get_system_response_string(response))
