#!/usr/bin/env bash
# capture.sh — record the current commit & working-tree state of a git repo
# into the usecase's `repos.yaml` so it can be restored later.
#
# Generic across all usecases: invoke from inside a usecase dir, or pass
# --usecase-dir <path>. Idempotent — re-running on the same repo updates
# the existing entry (matched by `path`).
#
# Usage:
#   bash scripts/capture.sh <repo_path> [--usecase-dir <dir>] [--note "..."]
#
# Examples:
#   bash scripts/capture.sh /Users/tchen7/MyProjects/atlassian-agi
#   bash scripts/capture.sh ~/MyProjects/foo --note "bar repo, branch frozen"

set -euo pipefail

err() { echo "ERROR: $*" >&2; exit 1; }
warn() { echo "WARN:  $*" >&2; }
info() { echo "INFO:  $*" >&2; }

# ---------- arg parsing ----------
REPO_PATH=""
USECASE_DIR=""
NOTE=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --usecase-dir) USECASE_DIR="$2"; shift 2 ;;
    --note)        NOTE="$2"; shift 2 ;;
    -h|--help)
      sed -n '2,18p' "$0"; exit 0 ;;
    *)
      if [[ -z "$REPO_PATH" ]]; then REPO_PATH="$1"; shift
      else err "unexpected arg: $1"; fi ;;
  esac
done
[[ -n "$REPO_PATH" ]] || err "usage: capture.sh <repo_path> [--usecase-dir <dir>] [--note '...']"

# Resolve repo path to absolute
REPO_PATH="$(cd "$REPO_PATH" 2>/dev/null && pwd -P)" || err "repo path not found or not a directory: $REPO_PATH"

# Resolve usecase dir (default = parent of this script)
if [[ -z "$USECASE_DIR" ]]; then
  USECASE_DIR="$(cd "$(dirname "$0")/.." && pwd -P)"
fi
[[ -d "$USECASE_DIR" ]] || err "usecase dir not found: $USECASE_DIR"

REPOS_YAML="$USECASE_DIR/repos.yaml"

# ---------- gather git state ----------
cd "$REPO_PATH"
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || err "not a git repo: $REPO_PATH"

COMMIT="$(git rev-parse HEAD)"
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
ORIGIN="$(git config --get remote.origin.url 2>/dev/null || echo '(no origin)')"
DIRTY_COUNT="$(git status --porcelain | wc -l | tr -d ' ')"
COMMIT_AUTHOR="$(git log -1 --format='%an <%ae>')"
COMMIT_DATE="$(git log -1 --format='%ai')"
COMMIT_SUBJECT="$(git log -1 --format='%s' | sed 's/"/\\"/g')"

info "repo:         $REPO_PATH"
info "commit:       $COMMIT  ($BRANCH)"
info "origin:       $ORIGIN"
info "dirty_count:  $DIRTY_COUNT"

# Capture porcelain entries if dirty (truncated to 20 for safety)
DIRTY_ENTRIES=""
if [[ "$DIRTY_COUNT" -gt 0 ]]; then
  DIRTY_ENTRIES="$(git status --porcelain | head -20 | sed 's/^/      - "/' | sed 's/$/"/')"
fi

# ---------- write YAML block ----------
# This script writes an APPEND-or-UPDATE entry. To keep the script dependency-free
# (no yq/python), we use a marker block per repo path. If the marker exists, the
# block is replaced in place; otherwise appended.
BEGIN_MARK="# --- BEGIN repo: $REPO_PATH ---"
END_MARK="# --- END repo: $REPO_PATH ---"

read -r -d '' NEW_BLOCK <<EOF || true
$BEGIN_MARK
  - path: $REPO_PATH
    origin: $ORIGIN
    branch: $BRANCH
    commit: $COMMIT
    commit_meta:
      author: $COMMIT_AUTHOR
      date: "$COMMIT_DATE"
      subject: "$COMMIT_SUBJECT"
    dirty_count: $DIRTY_COUNT
$( [[ -n "$DIRTY_ENTRIES" ]] && printf "    dirty_entries:\n%s\n" "$DIRTY_ENTRIES" )
$( [[ -n "$NOTE" ]] && printf "    notes: |\n      %s\n" "$NOTE" )
$END_MARK
EOF

# If repos.yaml doesn't exist, scaffold it
if [[ ! -f "$REPOS_YAML" ]]; then
  cat > "$REPOS_YAML" <<HDR
# repos.yaml — pinned repository state for $(basename "$USECASE_DIR")
# Generated by scripts/capture.sh.
# To restore: bash scripts/restore.sh

repos:
HDR
fi

# Update-in-place or append
if grep -qF "$BEGIN_MARK" "$REPOS_YAML"; then
  info "updating existing entry for $REPO_PATH"
  awk -v B="$BEGIN_MARK" -v E="$END_MARK" -v NEW="$NEW_BLOCK" '
    $0==B {print NEW; skip=1; next}
    skip && $0==E {skip=0; next}
    !skip {print}
  ' "$REPOS_YAML" > "$REPOS_YAML.tmp" && mv "$REPOS_YAML.tmp" "$REPOS_YAML"
else
  info "appending new entry for $REPO_PATH"
  printf "%s\n" "$NEW_BLOCK" >> "$REPOS_YAML"
fi

info "wrote: $REPOS_YAML"
[[ "$DIRTY_COUNT" -gt 0 ]] && warn "working tree had $DIRTY_COUNT uncommitted change(s); restore will NOT reproduce them — see dirty_entries"
echo "OK"
