// AUTOGENERATED — DO NOT EDIT. Run scripts/sync_widget_types.py.
// Mirrors agent_foundation.ui.input_modes.InputMode
export const InputMode = Object.freeze({
  FREE_TEXT: 'free_text',
  PRESS_TO_CONTINUE: 'press_to_continue',
  EXACT_STRING: 'exact_string',
  SINGLE_CHOICE: 'single_choice',
  MULTIPLE_CHOICE: 'multiple_choice',
});
