// AUTOGENERATED — DO NOT EDIT. Run scripts/sync_widget_types.py.
// Mirrors agent_foundation.ui.widget_protocol.WIDGET_TYPES
export const WIDGET_TEXT_INPUT = 'text_input';
export const WIDGET_SINGLE_CHOICE = 'single_choice';
export const WIDGET_MULTIPLE_CHOICE = 'multiple_choice';
export const WIDGET_DROPDOWN = 'dropdown';
export const WIDGET_TOGGLE = 'toggle';
export const WIDGET_TOOL_ARGUMENT_FORM = 'tool_argument_form';
export const WIDGET_CONFIRMATION = 'confirmation';
export const WIDGET_MULTI_INPUT = 'multi_input';
export const WIDGET_GROUPED = 'grouped';
export const WIDGET_DEFAULT = 'default';
export const WIDGET_TYPES = Object.freeze([
  'text_input',
  'single_choice',
  'multiple_choice',
  'dropdown',
  'toggle',
  'tool_argument_form',
  'confirmation',
  'multi_input',
  'grouped',
  'default',
]);
